### ISSUE TITLE
Prediction is significantly slow especially when data is large

### ISSUE THREAD

**Issue by sinnfashen** [microsoft/SynapseML#1327]
Here's an example (in python):

```
x = np.random.uniform(0,1,100000000)
y = np.random.uniform(0,1,100000000)
data = pd.DataFrame({'x':x, 'y':y})
spark_data = spark.createDataFrame(data)

lgb_dataset = lgb.Dataset(data[['x']], label=data['y'])
lgb_cfg = {'objective': 'regression_l1', 'num_trees': 128, 'max_depth': 5, 'num_leaves': 24, 'learning_rate': 0.2, 'lambda_l2': 10, 'min_gain_to_split': 10, 'verbosity': -1, 'min_data_in_leaf': 5000, 'feature_fraction': 1.0, 'num_threads': 0, 'tree_learner': 'serial', 'seed': 4}

native_mdl = lgb.train(params=lgb_cfg, train_set=lgb_dataset)  # Took 53s
native_mdl.predict(data[['x']])  # Took 3.5s

featurizer = VectorAssembler(inputCols=['x'], outputCol='features')
training_data = featurizer.transform(spark_data).persist()

  training_params = {
  'lambdaL2': 10,
  'learningRate': 0.2,
  'maxDepth': 5,
  'minGainToSplit': 10,
  'minDataInLeaf': 5000,
  'featureFraction': 1.0,
  'numLeaves': 24,
  'numIterations': 128,
  'metric': 'mae',
  'objective': 'regression_l1 seed=4',
    
  'parallelism': 'data_parallel',
  "numThreads": 0,
  "numTasks": 0,
}

trainer = LightGBMRegressor(featuresCol='features', labelCol='y', **training_params)

model = trainer.fit(training_data) # Took 9s (good as expected)
model.transform(training_data).cache().count()  # Took 9.8 mins!
```

Not sure if I'm doing anything wrong. 
I was wondering could it be due to the[ row-wise prediction](https://github.com/microsoft/SynapseML/blob/master/lightgbm/src/main/scala/com/microsoft/azure/synapse/ml/lightgbm/LightGBMRegressor.scala#L117)? And any suggestion on how could it be faster? The current time cost difference makes it hard to use especially in cases such as cross-validation.

**Comment by imatiach-msft** [comment]
@sinnfashen have you tried using ONNX with lightgbm, there is an example here:
https://microsoft.github.io/SynapseML/docs/features/onnx/ONNX%20-%20Inference%20on%20Spark/
that should make predictions much faster.  I think it may be slow because we call one row at a time which has high constant cost, instead of batching rows.  I believe there are actually some recent optimizations and a new method available in native lightgbm API to reduce the constant cost, but I haven't yet had the time to update to use the new API.  Using ONNX should get around all of that.
