### ISSUE TITLE
mmlspark lightgbm support for spark2.4

### ISSUE THREAD

**Issue by liuyxmax** [microsoft/SynapseML#1411]
I am working on lightgbm on spark. Since Spark2.4 on my company doesn't support synapseML, I am trying old version of mmlspark.
I am doing as this link [[mmlspark](https://github.com/nubank/mmlspark). ](https://github.com/nubank/mmlspark/blob/1.0.0-rc1-NUBANK/docs/lightgbm.md). Spark on company is offline,  and has an old version of mmlspark and cannot upgrade:
 `pip show mmlspark
Version: 0.0.11111111
`. 
 To distribute mmlspark to cluster, I need to upload a jar when initialize spark. My question is: 
1. Does 0.0.11111111 support lightgbm, if not is there a way to install mmlspark  1.0.0 offline?
2. If  0.0.11111111 support lightgbm, could you provide jar with this version? Thank you.

**Comment by mhamilton723** [comment]
Hey @liuyxmax we really suggest updating to spark 3 as 2.4 is now several years old with potential security ramifications. 

However to use an older version please 

1. uninstall that pip package (not sure why that's on pip and we have just moved to delete it so that it doesn't confuse others)
2. Follow older install guidance [here](https://github.com/microsoft/SynapseML/tree/v1.0.0-rc3) 

Such as 

```
import pyspark
spark = pyspark.sql.SparkSession.builder.appName("MyApp") \
            .config("spark.jars.packages", "com.microsoft.ml.spark:mmlspark_2.11:1.0.0-rc3") \
            .config("spark.jars.repositories", "https://mmlspark.azureedge.net/maven") \
            .getOrCreate()
import mmlspark
```

**Comment by yiming-lzx** [comment]
> 

the Link not work
