### ISSUE TITLE
LightGBM does not save numIteration to string or native model

### ISSUE THREAD

**Issue by djshen** [microsoft/SynapseML#1494]
**Describe the bug**
When the LightGBM model early stopped, `LightGBMBooster.numIterations` is set and this value will be passed to `lightgbmlib` while calling `predictForCSR` or `predictForMat`. However, `saveToString` and `saveNativeModel` do not save this information. Therefore, when we load the model from the saved string or native model again, the predictions would be different from the original model.

**To Reproduce**
Steps to reproduce the behavior, code snippets encouraged

**Expected behavior**
According to the LightGBM python library, it saves the best iteration by default.
https://github.com/microsoft/LightGBM/blob/v3.3.2/python-package/lightgbm/basic.py#L3298

**Info (please complete the following information):**
 - SynapseML Version: 0.9.5
 - Spark Version: 3.2.0
 - Spark Platform: local

** Stacktrace**
```
Please post the stacktrace here if applicable
```

If the bug pertains to a specific feature please tag the appropriate [CODEOWNER](https://github.com/Microsoft/SynapseML/blob/master/CODEOWNERS) for better visibility
@imatiach-msft 

**Additional context**

AB#1764742

**Comment by mhamilton723** [comment]
Tagging in @imatiach-msft @svotaw

**Comment by svotaw** [comment]
@djshen  Can you provide code examples and specific "incorrect" model output for saveToString or saveNativeModel?  In my testing locally, if "early stopping" is hit, the returned model from `fit` only serializes the used iterations in `saveToString` (which uses the LightGBM library to actually do the serialization). What do you mean by _"`saveToString` and `saveNativeModel` do not save this information"_?  i.e. , if early stopping only results in 5 iterations, I see only the 5 iterations in the output, not the original `numIterations` number of trees.  A serialized model does not explicitly include "bestIteration" index since it just relies on the count of model trees.

If I save a model that ended early and load it back, then `numIterations` and `bestIteration` are indeed -1 for the in-memory object, but that just means use all iterations in the model (which will just be the "used" ones since we don't save the extraneous ones).

Perhaps some path you are using has a bug that I did not try or I'm not completely understanding the problem, which is why I'd like to see a specific example of how you are using the serialized models and where you actually hit a difference.

**Comment by svotaw** [comment]
nevermind, found the issue.  fixing it.  :)

**Comment by svotaw** [comment]
Fixed with this PR:
https://github.com/microsoft/SynapseML/pull/1497

Build here:
SynapseML Build and Release Information
Maven Coordinates
com.microsoft.azure:synapseml_2.12:0.9.5-104-9657a531-SNAPSHOT

Maven Resolver
https://mmlspark.azureedge.net/maven

**Comment by djshen** [comment]
Hi @svotaw,

Thank you for the fix! We will test this build later.
