### ISSUE TITLE
pip install lightgbm

### ISSUE THREAD

**Issue by songhappy** [microsoft/SynapseML#1621]
Currently, the only way to install python synapseml lightgbm  is from spark configuration. 
```
import pyspark
spark = pyspark.sql.SparkSession.builder.appName("MyApp")
        .config("spark.jars.packages", "com.microsoft.azure:synapseml_2.12:0.10.0") # Please use 0.10.0 version for Spark3.2 and 0.9.5-13-d1b51517-SNAPSHOT version for Spark3.1
        .config("spark.jars.repositories", "https://mmlspark.azureedge.net/maven")
        .getOrCreate()
import synapse.ml
```
pip install synapselml does not pull the jar

**Describe the solution you'd like**
it should support pip install or conda install package into a conda environment 

BTW, where is the source code of LightGBMClassifier and so on. it only has LightGBMClassificationModel on the website of
https://github.com/microsoft/SynapseML/tree/master/lightgbm/src/main/python/synapse/ml/lightgbm

AB#1936959

**Comment by mhamilton723** [comment]
Thanks for trying SynapseML @songhappy yes this is by design as our project has python and java components. We actually have a feature request to core spark team to try to give a better design for the community. Please vote and comment on this to drive community support 

https://issues.apache.org/jira/browse/SPARK-39779

**Comment by songhappy** [comment]
where is the source code of LightGBMClassifier pyspark?
