### ISSUE TITLE
lightGBM multi-class classifier

### ISSUE THREAD

**Issue by songhappy** [microsoft/SynapseML#1644]
**Is your feature request related to a problem? Please describe.**
Currently, LightGBMClassifier does not have a way to set numClasses for multiple classes.
https://mmlspark.blob.core.windows.net/docs/0.10.0/scala/com/microsoft/azure/synapse/ml/lightgbm/LightGBMClassifier.html

**Describe the solution you'd like**
a method of setNumClasses should be added to LightGBMClassifier to handle multi-classification 

AB#1966816

**Comment by svotaw** [comment]
Can you explain more about what you are asking?  The number of classes is detected by the number of unique values in the labels column. You wish to set it explicitly?

**Comment by songhappy** [comment]
yes, is it possible to set up num_class just like objective expressively?

**Comment by svotaw** [comment]
not currently, it is always auto-calculated from the data.  Out of curiosity, can you explain the scenario where you would want to set it explicitly?  This would be a feature request, since it would require a code change.

You could try using setPassThroughArgs() to set num_class explicitly, and it looks like the code will honor it (just visual inspection), but we don't test for that particular scenario. And it will still count the unique instances of label values on initialization, it just will see that there is an explicit override already when it tries to create the LightGBM params string (I think).

**Comment by svotaw** [comment]
please reopen if you have any more questions
