### ISSUE TITLE
demo usage for setPassThroughArgs

### ISSUE THREAD

**Issue by shexuan** [microsoft/SynapseML#1741]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I look for demo codes like other respositry best practice. I want to set force_row_wise for lightgbm and I find a related links about using `setPassThroughArgs`. But it's disappointed to find no demos.

Should I use `new LightGBMClassifier().setPassThroughArgs("force_row_wise=true")` OR .setPassThroughArgs("force_row_wise->true") ? OR others?

**Describe the solution you'd like**
A demo usage for  `setPassThroughArgs` would be greatly appreciate.

**Additional context**
scala lightgbm 
version 0.10.0.

**Comment by JessicaXYWang** [comment]
Hi shexuan, thank you for raising this question.

for Python, you can use:
```
model = LightGBMRegressor(passThroughArgs="force_row_wise=true")
```

and for Scala, you can use:
```
new LightGBMRegressor().setPassThroughArgs("force_row_wise=true")
```

You may also want to check this issue: https://github.com/microsoft/SynapseML/issues/1642

Let me know if this works.

**Comment by shexuan** [comment]
> Hi shexuan, thank you for raising this question.
> 
> for Python, you can use:
> 
> ```
> model = LightGBMRegressor(passThroughArgs="force_row_wise=true")
> ```
> 
> and for Scala, you can use:
> 
> ```
> new LightGBMRegressor().setPassThroughArgs("force_row_wise=true")
> ```
> 
> You may also want to check this issue: #1642
> 
> Let me know if this works.

Another questions，can negBaggingFraction work with featureFratcin at the same time?

**Comment by JessicaXYWang** [comment]
negBaggingFraction and featureFraction should be able to work at the same time. 

Hi @svotaw ,can you help to confirm that negBaggingFraction should works the same way in SynapseML as neg_bagging_fraction works in [LightGBM](https://lightgbm.readthedocs.io/en/v3.3.2/Parameters.html#neg_bagging_fraction). Which means 
1. to enable this, you need to set baggingFreq and posBaggingFraction as well
2. if both posBaggingFraction and negBaggingFraction are set to 1.0, balanced bagging is disabled
3. if balanced bagging is enabled, baggingFraction will be ignored

**Comment by svotaw** [comment]
Yes, we (SynapseML) set all the params to LightGBM that we expose directly (this includes baggingFraction, posBaggingFraction, and negBaggingFraction).  So you can use setNegBaggingFraction (or negBaggingFraction=x in python) rather than setPassThroughArgs.

setPassThroughArgs is really only for cases where we do not expose a LightGBM param directly, and you want to directly add something to LightGBM args that we don't set for you. You will need to follow any documentation of LightGBM args if you are setting them manually.

Yes, we should add an example for usage of setPassThroughArgs. I will at least put an example in the doc string. There are some example usages in Vowpal Wabbit. Since this is just sending args directly to the underlying LightGBM native library, it is up to you to format them correctly as documented by LightGBM. They use the "=" sign or " " to separate names from values, "--" for some args that don't have values, and spaces to separate multiple args. Docs for LightGBM parameters can be found here: https://lightgbm.readthedocs.io/en/v3.3.2/Parameters.html.

We always defer to the setPassThroughArgs first, so if you set both setPassthroughArgs("neg_bagging_fraction=0.5") and setNegBaggingFraction(0.6), the former will be used.

**Comment by svotaw** [comment]
> Another questions，can negBaggingFraction work with featureFratcin at the same time?

I believe you have to set both. SynapseML is just a wrapper around LightGBM, so you'll need to follow the LightGBM docs for particular parameters. https://lightgbm.readthedocs.io/en/v3.3.2/Parameters.html

**Comment by svotaw** [comment]
https://github.com/microsoft/SynapseML/pull/1749

**Comment by shexuan** [comment]
> 

Thanks a lot.
