### ISSUE TITLE
[QUESTION] Is it necessary to pass categoricalSlotNames if I'm one-hot encoding categoricals?

### ISSUE THREAD

**Issue by flavajava** [microsoft/SynapseML#1844]
I am using pyspark (3.2.1) with SynapseML 0.10.2 and am looking to train a LightGBMClassifier on it (across multiple executors). My dataset has a number of categorical variables. I am one-hot encoding each of them like this (in Python):

`            col_indexer = StringIndexer(inputCol=col, outputCol=index_col_name)
            df = col_indexer.fit(df).transform(df)
            onehotencoder_col_vector = OneHotEncoder(inputCol=index_col_name, outputCol=col + '__VECTOR')
            df = onehotencoder_col_vector.fit(df).transform(df)
`

and then using a VectorAssembler like this:

`
featurizer = VectorAssembler(inputCols=get_spark_feature_columns(FEATURE_COLS, CATEGORICAL_FEATURE_COLS), outputCol='features')
train_df_featurized = featurizer.transform(train_and_val_df)

`

Given that I have done the above, do I still need to pass categoricalSlotNames with the former column names?

Thanks so much

**Comment by imatiach-msft** [comment]
@flavajava I don't believe so, we have this automatic logic for categorical attributes which are set by OneHotEncoder and propagated by VectorAssembler:

https://github.com/microsoft/SynapseML/blob/d8d523c6ba603d62744b06608265bb5bfbdad8df/lightgbm/src/main/scala/com/microsoft/azure/synapse/ml/lightgbm/LightGBMBase.scala#L172

Hence, we should get the categoricalIndexes automatically, since I believe the attributes are set correctly.  However, it's fine to specify the categorical indexes multiple times, since we get distinct indexes anyway in the line:

https://github.com/microsoft/SynapseML/blob/d8d523c6ba603d62744b06608265bb5bfbdad8df/lightgbm/src/main/scala/com/microsoft/azure/synapse/ml/lightgbm/LightGBMBase.scala#L196

I wish there was an easier way on a trained model to "see" which categorical indexes were set through the pyspark API.  Regardless, if you save the lightgbm model file in native format it should state what the categorical indexes are - although it can be quite difficult to read/understand if you are not familiar with the format.

**Comment by imatiach-msft** [comment]
Closing question - please reopen again if there are any follow-up questions.  Thank you!
