### ISSUE TITLE
Boost from prediction support

### ISSUE THREAD

**Issue by clamoris** [microsoft/SynapseML#418]
Looks like there is no way currently to provide initial scores to LightGBMClassifier. Is this true? Will this be supported in future versions?

**Comment by imatiach-msft** [comment]
@clamoris yes, you are correct, please see this issue: https://github.com/Azure/mmlspark/issues/382
I believe LightGBM would need to be modified first before we could add the support.  Please let me know if you have any questions.  I will close this issue later today since it is a duplicate of the above.
