### ISSUE TITLE
lightgbm still can not do multiclass?

### ISSUE THREAD

**Issue by puyvqi** [microsoft/SynapseML#444]
![2018-11-22 17-21-39](https://user-images.githubusercontent.com/11178311/48893834-39549500-ee7c-11e8-9ba3-eba26bccdc9a.png)
![2018-11-22 17-24-10](https://user-images.githubusercontent.com/11178311/48893860-483b4780-ee7c-11e8-94c1-8139ab1708dd.png)
look! I got 3 classes,but when the native lightgbm builting booster,it always throw a error to me!
![image](https://user-images.githubusercontent.com/11178311/48894013-a9fbb180-ee7c-11e8-8445-06bcf624cd23.png)
this method throw the error ,because the numclass it calculateing is always 1?
is this a lightgbm's bug?or a mmlspark's?
why did still no one try to fix it?
is there some way to work around to let me build a normal booster for multiclass task?
![2018-11-22 17-22-25](https://user-images.githubusercontent.com/11178311/48894347-884efa00-ee7d-11e8-8bc3-8b7d5a261077.png)
![image](https://user-images.githubusercontent.com/11178311/48894071-c4358f80-ee7c-11e8-8e98-fb24623443c8.png)

**Comment by imatiach-msft** [comment]
@puyvqi sorry about the trouble you are having, indeed, there is already an issue for this, it is an enhancement I am planning to add in the future: https://github.com/Azure/mmlspark/issues/342
There was a recent change that allowed you to set the object which wasn't exposed before, and I think it's partly due to this that the issue has become worse, since you are allowed to explicitly set multiclass objective for the classifier.
However, since LightGBMClassifier follows spark ML's API, you could use OneVsRest model to make the binary classifier a multiclass classifier:
https://spark.apache.org/docs/latest/api/scala/index.html#org.apache.spark.ml.classification.OneVsRest
But this won't be as optimal as using the native multiclass classifier from lightgbm.
